\context ChordNames
	\chords {
		\set majorSevenSymbol = \markup { "maj7" }
		\set chordChanges = ##t

		% intro
		d2. g2. a2. a2.
		d2. g2. a2. a2.

		% gloria...
		d2. a2. d2. d2.:7
		g2. a2. d2. d2.
		g2. a2. d2. d2.
		g2. a2. d2. d2.

		% te alabamos...
		g2. g2. a2. a2.
		fis2.:m fis2.:m b2.:m b2.:m
		g2. g2. a2. a2.
		d2. d2. d2.:7 d2.:7
		g2. g2. a2. r2.
		d2. g2. a2. a2.

		% gloria...
		d2. a2. d2. d2.:7
		g2. a2. d2. d2.
		g2. a2. d2. d2.
		g2. a2. d2. d2.

		% sennor jesus...
		g2. g2. a2. a2.
		fis2.:m fis2.:m b2.:m b2.:m
		g2. g2. a2. a2.
		d2. d2. d2.:7 d2.:7
		g2. g2. a2. r2.
		d2. g2. a2. a2.

		% gloria...
		d2. a2. d2. d2.:7
		g2. a2. d2. d2.
		g2. a2. d2. d2.
		g2. g2. a2. r2.
		d2. g2. d2. d2.
	}
